Mahasiswa dapat menginput dari file dan keyboard, dan mengoutpput ke file dan layar

Input Keyboard

In [1]:
# Contoh input dari user
variabel = input('Masukkan nama Anda: ')

In [15]:
# Contoh penggunaan input dalam menghitung biaya
saldo = 100000

belanja = int(input('Masukkan biaya belanja Anda: '))

total = saldo - belanja
print('Biaya belanja Anda adalah Rp{0:0.2f}'.format(belanja)) # Contoh output = Biaya belanja Anda adalah Rp10000.00
print('Sisa saldo Anda adalah Rp{0:0.2f}'.format(total)) # Contoh output = Sisa saldo Anda adalah Rp90000.00

Biaya belanja Anda adalah Rp34500.00
Sisa saldo Anda adalah Rp65500.00


In [43]:
# Input file
import numpy as np
data = np.loadtxt('data_eksperimen.txt', skiprows=5, unpack=True)
print(data)

np.array(data)

[[  0.     1.     2.     3.     4.     5.     6.     7.     8.     9.
   10.    11.    12.  ]
 [  0.     0.5    1.     1.5    2.     2.5    3.     3.5    4.     4.5
    5.     5.5    6.  ]
 [180.   182.   178.   165.   160.   148.   136.   120.    99.    83.
   55.    35.     5.  ]
 [  3.5    4.5    4.     5.5    2.5    3.     2.5    3.     4.     2.5
    3.6    1.75   0.75]]


array([[  0.  ,   1.  ,   2.  ,   3.  ,   4.  ,   5.  ,   6.  ,   7.  ,
          8.  ,   9.  ,  10.  ,  11.  ,  12.  ],
       [  0.  ,   0.5 ,   1.  ,   1.5 ,   2.  ,   2.5 ,   3.  ,   3.5 ,
          4.  ,   4.5 ,   5.  ,   5.5 ,   6.  ],
       [180.  , 182.  , 178.  , 165.  , 160.  , 148.  , 136.  , 120.  ,
         99.  ,  83.  ,  55.  ,  35.  ,   5.  ],
       [  3.5 ,   4.5 ,   4.  ,   5.5 ,   2.5 ,   3.  ,   2.5 ,   3.  ,
          4.  ,   2.5 ,   3.6 ,   1.75,   0.75]])

In [57]:
# Pembuatan file
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
c = np.array([11, 12, 13, 14, 15])
d = zip(a, b, c)
print(d)

e = np.array(list(d))
print(e)

# Mengiris array
print(e[4, 2]) # Output = 15

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
15
