Mahasiswa mengetahui perbedaan list dan array

Array multidimensi dan matriks

In [1]:
import numpy as np
b = np.array([[1., 2., 3.], [4., 5., 6.]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [11]:
# Indeksasi array multidimensi
print(b[0, 1]) # hanya untuk array
print(b[0] [1]) # untuk list dan array

2.0
2.0


In [12]:
# Operasi matriks
print(b + b)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]


In [13]:
2 * b

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [14]:
b / 4

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ]])

In [15]:
pow(b,2)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [16]:
b - 2

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.]])

Fungsi np.array mengubah list dua dimensi menjadi array dua dimensi. Array membuat semua elemen memiliki jenis data yang sama sedangkan list memiliki jenis data yang berbeda-beda.

In [2]:
# Array dengan angka 1
a = np.ones((3, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [3]:
# Matriks identitas dua dimensi dengan nilai satu pada diagonal utama
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
a = np.arange(8)
print(a)

[0 1 2 3 4 5 6 7]


In [6]:
a = np.reshape(a, (2, 4))
print(a)

[[0 1 2 3]
 [4 5 6 7]]
