Mahasiswa dapat membuat array, mengindeks, dan mengoperasikannya

Array

Membuat array 1D

In [2]:
# List menjadi array
import numpy as np
a = [1, 2, 3, 4, 5]
b = np.array(a)
print(b)

[1 2 3 4 5]


Linspace: Membuat N titik dengan jarak yang sama antara titik awal dan titik akhir. Bentuknya adalah linspace(start, stop, N).

Logspace: Bentuknya adalah logspace(start, stop,N). Namun, pada bagian start  dan stop mengacu pangkat 10 artinya array dimulai pada 10^start dan berakhir pada 10^stop

In [3]:
# Linspace
c = np.linspace(0, 10, 5)
print(c)

# Logspace
d = np.logspace(0, 10, 5)
print(d)

[ 0.   2.5  5.   7.5 10. ]
[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10]


In [4]:
# Arange
e = np.arange(0, 10, 2) # Bentuk fungsi arange adalah arange(start, stop, step)
print(e)

[0 2 4 6 8]


In [6]:
np.zeros(5) # Membuat array dengan 5 elemen 0

array([0., 0., 0., 0., 0.])

In [7]:
np.ones(5) # Membuat array dengan 5 elemen 1

array([1., 1., 1., 1., 1.])

In [8]:
np.eye(5) # Membuat array dengan 5x5 elemen 1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.diag([1, 2, 3, 4, 5]) # Membuat array dengan diagonal 1, 2, 3, 4, 5

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

Operasi matematis array

In [10]:
z = np.linspace(-1, 5, 7)
print(z)

[-1.  0.  1.  2.  3.  4.  5.]


In [11]:
z*2 # Mengalikan semua elemen array dengan 2


array([-2.,  0.,  2.,  4.,  6.,  8., 10.])

In [12]:
z/2 # Membagi semua elemen array dengan 2

array([-0.5,  0. ,  0.5,  1. ,  1.5,  2. ,  2.5])

In [13]:
pow(z, 2) # Mengkuadratkan semua elemen array

array([ 1.,  0.,  1.,  4.,  9., 16., 25.])

In [14]:
z+7 # Menambahkan semua elemen array dengan 7

array([ 6.,  7.,  8.,  9., 10., 11., 12.])

In [15]:
z-10 # Mengurangkan semua elemen array dengan 10

array([-11., -10.,  -9.,  -8.,  -7.,  -6.,  -5.])

In [16]:
pow((z+4), 2) # Menambahkan semua elemen array dengan 4, kemudian mengkuadratkan semua elemen array

array([ 9., 16., 25., 36., 49., 64., 81.])

In [17]:
np.sin(z) # Menghitung sin dari semua elemen array

array([-0.84147098,  0.        ,  0.84147098,  0.90929743,  0.14112001,
       -0.7568025 , -0.95892427])

In [18]:
np.exp(z) # Menghitung eksponen dari semua elemen array

array([  0.36787944,   1.        ,   2.71828183,   7.3890561 ,
        20.08553692,  54.59815003, 148.4131591 ])

In [19]:
# Membuat 2 array

# Buat array untuk nilai x
x = np.linspace(-3.14, 3.14, 5)

# Hitung nilai cos^2(x)
cos2x = np.cos(2*x)

# Hitung nilai sin(x)
sinx = np.sin(x)

# Cetak array
print("Nilai cos^2(x):", cos2x)
print("Nilai sin(x):", sinx)

Nilai cos^2(x): [ 0.99999493 -0.99999873  1.         -0.99999873  0.99999493]
Nilai sin(x): [-0.00159265 -0.99999968  0.          0.99999968  0.00159265]


In [20]:
tambah = cos2x + sinx
print("Hasil penjumlahan cos^2(x) dan sin(x):", tambah)

Hasil penjumlahan cos^2(x) dan sin(x): [ 9.98402274e-01 -1.99999841e+00  1.00000000e+00  9.51204295e-07
  1.00158758e+00]


In [21]:
kurang = cos2x - sinx
print("Hasil pengurangan cos^2(x) dan sin(x):", kurang)

Hasil pengurangan cos^2(x) dan sin(x): [ 1.00158758e+00  9.51204295e-07  1.00000000e+00 -1.99999841e+00
  9.98402274e-01]


In [22]:
kali = cos2x * sinx
print("Hasil perkalian cos^2(x) dan sin(x):", kali)

Hasil perkalian cos^2(x) dan sin(x): [-0.00159264  0.99999841  0.         -0.99999841  0.00159264]


In [23]:
bagi = cos2x / sinx
print("Hasil pembagian cos^2(x) dan sin(x):", bagi)

Hasil pembagian cos^2(x) dan sin(x): [-627.88000861    0.99999905           inf   -0.99999905  627.88000861]


C:\Users\asus6\AppData\Local\Temp\ipykernel_26076\4040277493.py:1: RuntimeWarning: divide by zero encountered in divide
  bagi = cos2x / sinx
